In [5]:
# 1. Create a null vector of size 10 but the fifth value which is 1.
import numpy as np
k = np.zeros(10)
k[4] = 1
print(k)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [10]:
# 2. Create a vector with values ranging from 10 to 49.
import numpy as np
m = np.arange(10,50)
print(m)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [12]:
# 3. Create a 3x3 matrix with values ranging from 0 to 8
x = np.arange(0,9).reshape(3,3)
print(x)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [17]:
# 4. Find indices of non-zero elements from [1,2,0,0,4,0]
m = np.array([1,2,0,0,4,0])
print("Indices of non-zero element are :")
for i in range(len(m)):
    if m[i] != 0:
        print(i)

Indices of non-zero element are :
0
1
4


In [29]:
# 5. Create a 10x10 array with random values and find the minimum and maximum values.
import random
x = np.random.randint(0,100,size=(10,10))
print("array is:",x)
mx = x.max()
mi = x.min()
print("Minimum value is :",mi)
print("Maximum value is :",mx)

array is: [[51  2 28 53 49 43 18 11 91 14]
 [29 39 60 34 34 87 16 26 87 92]
 [82 35  7 50 63 83 72 80 49 84]
 [14 25 80 77 13  3 48 69 23 94]
 [42  5 64 28 67  3 92 33 40 89]
 [85 86 58 92 89  2 48 99 51 18]
 [94 29 87 93 50 24 80 27 76 47]
 [64 57 20 92 49 53 23 89 20 56]
 [41 61 55 30 29  0 85 84 14 60]
 [15 97 30 62 67 67 31 61 71 57]]
Minimum value is : 0
Maximum value is : 99


In [35]:
# 6. Create a random vector of size 30 and find the mean value.
np.random.seed(6)
k = np.random.randint(0,50,size=(30))
print("vector is",x)
m = k.mean()
print("mean value is",m)

vector is [[51  2 28 53 49 43 18 11 91 14]
 [29 39 60 34 34 87 16 26 87 92]
 [82 35  7 50 63 83 72 80 49 84]
 [14 25 80 77 13  3 48 69 23 94]
 [42  5 64 28 67  3 92 33 40 89]
 [85 86 58 92 89  2 48 99 51 18]
 [94 29 87 93 50 24 80 27 76 47]
 [64 57 20 92 49 53 23 89 20 56]
 [41 61 55 30 29  0 85 84 14 60]
 [15 97 30 62 67 67 31 61 71 57]]
mean value is 22.166666666666668
